services:
  db:
    image: postgres:17-alpine
    container_name: auth_system_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

    ports:
      - '5432:5432'
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
